import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  container: {
    display: 'flex',
    flexDirection: 'column' as 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    fontFamily: '"Titillium Web", Arial, sans-serif',
    color: '#014283',
    lineHeight: '1.6',
    textAlign: 'center',
    maxWidth: '800px',
    margin: '0 auto',
  },
  title: {
    color: '#47D4DD',
    marginBottom: '20px',
  },
  instructions: {
    fontSize: '18px',
    marginBottom: '30px',
  },
  buttonContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
    marginBottom: '30px',
  },
  button: {
    padding: '10px 20px',
    fontSize: '16px',
    cursor: 'pointer',
    backgroundColor: '#F4FFFE',
    color: '#014283',
    border: '2px solid #47D4DD',
    borderRadius: '5px',
    fontWeight: 'bold',
    textTransform: 'none',
    width: '100px',
    textAlign: 'center',
  },
  activeButton: {
    padding: '10px 20px',
    fontSize: '16px',
    cursor: 'pointer',
    backgroundColor: '#47D4DD',
    color: '#fff',
    border: '2px solid #47D4DD',
    borderRadius: '5px',
    fontWeight: 'bold',
    textTransform: 'none',
    width: '100px',
    textAlign: 'center',
  },
  tutorialContainer: {
    width: '100%',
    maxWidth: '600px',
    padding: '20px',
    border: '1px solid #47D4DD',
    borderRadius: '10px',
    backgroundColor: '#F4FFFE',
  },
  tutorialTitle: {
    fontSize: '24px',
    marginBottom: '15px',
    color: '#014283',
  },
  tutorialList: {
    listStyleType: 'decimal',
    paddingLeft: '20px',
    textAlign: 'left',
  },
  footer: {
    marginTop: '30px',
    fontSize: '16px',
  },
  link: {
    color: '#47D4DD',
    textDecoration: 'none',
    fontWeight: 'bold',
  },
  downloadButton: {
    padding: '10px 20px',
    fontSize: '16px',
    cursor: 'pointer',
    backgroundColor: '#F4FFFE',
    color: '#014283',
    border: '2px solid #47D4DD',
    borderRadius: '5px',
    fontWeight: 'bold',
  },
}; 